### PR TITLE
fix(expo-cli): refer current sdk from empty-checked version string

### LINKED ISSUE #1331: expo client:install:ios/android should work outside of a project directory
In this case it should just install the latest version of the client. cc @byCedric

### PR DESCRIPTION
**Pull request by byCedric**
This fixes #1331

### CODE REVIEW

**Comment by brentvatne** [comment]
i'm not sure this would address the problem, because the command will exit before this code can execute due to this: https://github.com/expo/expo-cli/blob/ac26c9c4f06fe3ba76f30b81f818ac9661de777b/packages/expo-cli/src/commands/client/index.js#L256-L269

i think the easiest fix here is to just call `Simulator.upgradeExpoAsync()` when no config is found

**Comment by byCedric** [comment]
I see your point, but the no-project exception is thrown from the `findProjectRootAsync` (line 257), and skips line 258 + 259. So the part you highlighted will log and continue below.

I'm actually trying to refactor this as we speak, to make it way more readable. 😄

**Comment by byCedric** [comment]
I broke up the functionality and put some logic into a utility file. If you want a quick fix, merge this. [PR 1358 fixes this issue too](https://github.com/expo/expo-cli/pull/1358), but in a nicer way 😄

**Comment by brentvatne** [comment]
:) i'll go with 1358, thanks @byCedric!

**Pull request closed without merging**
