### PR TITLE
Upgrade copy-webpack-plugin to 6.0.1

### PR DESCRIPTION
**Pull request by spoilerdo**
Regarding to this issue:

https://github.com/expo/expo-cli/issues/2210 related issue

I upgraded the package version.
If there are any questions let me know.

### CODE REVIEW

**Comment by EvanBacon** [comment]
Please don't open PRs without testing the changes. This code doesn't even compile.

**Comment by ide** [comment]
A PR that bumps a dependency, especially a major version, needs to explain why this change is safe.

This often includes going through the dependency's change log / upgrade guide and explaining why the changes are safe for this project. Additionally, writing a test plan that explains how you verified correctness (and how someone else can verify correctness the next time this code is touched) is important.

**Comment by spoilerdo** [comment]
The reason of bumping the version can be seen in the related issue.
Though it was clear that if I added a related issue that the explenation would be in there.

**Comment by EvanBacon** [comment]
completed in https://github.com/expo/expo-cli/pull/2334 -- in the future please ensure the tests pass and the package can be used locally.

**Pull request closed without merging**
