### PR TITLE
[dev-tools] Update graphql related dependencies version

### PR DESCRIPTION
**Pull request by vvakame**
refs #2025

### CODE REVIEW

**Comment by vvakame** [comment]
CI failed, same as master branch.

**Comment by vvakame** [comment]
CI passed

**Comment by martinheidegger** [comment]
I think this PR might fix the "Error loading DevTools" error [see more here](https://forums.expo.io/t/error-loading-devtools/39584/4?u=consento). It mentionst hat the cli should use the same graphql version as react-native references. Which is not `^14.0.0` as dependency of `eslint-plugin-react@1.4.1` which is a dependency of react-native@0.62.2 (newer versions of react-native have newer dependencies.

**Comment by dacevedo12** [comment]
Any updates on this?

**Comment by RWOverdijk** [comment]
@EvanBacon sorry for the direct ping. Is this on anyone's radar? Based on [this comment here](https://github.com/graphql/graphql-js/issues/2503#issuecomment-830614404) I think this is also the cause of our CD being broken because expo-cli can't be a dev dependency (we use graphql and the versions collide).

```
Body must be a string. Received: undefined.
  at devAssert (/Users/me/projects/hybrid/my-project/node_modules/graphql/jsutils/devAssert.js:12:11)
...
  at Object.<anonymous> (/Users/me/projects/hybrid/my-project/node_modules/graphql-tools/src/stitching/introspectSchema.ts:7:48)
```

**Comment by RWOverdijk** [comment]
I have to uninstall expo-cli locally, and install it again to deploy with every merge we do. This is getting pretty tedious.

Could someone chime in on this, please?

**Comment by jedahan** [comment]
Would also like to see this updated; having the same issue.

**Comment by bombillazo** [comment]
PLEASE someone merge this!

**Comment by EvanBacon** [comment]
[dev tools UI is now deprecated](https://medium.com/the-exponent-log/sunsetting-the-web-ui-for-expo-cli-ab12936d2206)

**Comment by RWOverdijk** [comment]
> [dev tools UI is now deprecated](https://medium.com/the-exponent-log/sunsetting-the-web-ui-for-expo-cli-ab12936d2206)

Works for me 😄 Thanks for letting us know.

**Pull request closed without merging**
