### PR TITLE
fix(webpack-config): read correct values from config

### PR DESCRIPTION
**Pull request by jaulz**
Currently, for example the `serviceWorker` is not correctly read from `app.json` because it's always overridden by the default value `{}`. This fix returns the property from `app.json` if it's truthy and an object.

### CODE REVIEW

**Comment by jaulz** [comment]
@EvanBacon could you please have a look at this PR? I think it's still valid.

**Comment by EvanBacon** [comment]
I'd like to just delete and or drastically reduce the values in `app.json` due to type safety and cross-framework compatibility. If you'd still like to land this then please add tests to `packages/webpack-config/src/utils/__tests__/config-test.js`

**Comment by jaulz** [comment]
Sure, will add them beginning of next week!

**Comment by jaulz** [comment]
@EvanBacon done 😊

**Pull request merged**
