### PR TITLE
update semver to fix vulnerabilities

### LINKED ISSUE #4755: Vulnerability detected for Semver
### Summary

Several packages has pinned `"semver": "7.3.2"`, for example:

https://github.com/expo/expo-cli/blob/af2874cf685e6562c74ab597cdb099750c84a3fd/packages/image-utils/package.json#L39

See: [`semver vulnerable to Regular Expression Denial of Service`](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) for more details.

```
semver: 7.3.2
   ├─ ID: 1093264
   ├─ Issue: semver vulnerable to Regular Expression Denial of Service
   ├─ URL: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
   ├─ Severity: moderate
   ├─ Vulnerable Versions: >=7.0.0 <7.5.2
   ├─ Patched Versions: >=7.5.2
   └─ Recommendation: Upgrade to version 7.5.2 or later
 ```

### Environment

`@expo/prebuild-config@npm:6.2.6`=> `@expo/image-utils@npm:0.3.2`

### Please specify your device/emulator/simulator platform, model and version

NA

### Error output

_No response_

### Reproducible demo or steps to reproduce from a blank project

Check vulnerabilities, e.g.: `yarn audit`.

### PR DESCRIPTION
**Pull request by janpe**
# Why

Fix vulnerability with semver (https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795)

# How

Update semver to `> 7.5.3`

closes #4755

### CODE REVIEW

**Comment by AugustoAleGon** [comment]
This should be merge soon.

**Comment by janpe** [comment]
@byCedric do you think this would be a reasonable thing to have merged?

**Comment by byCedric** [comment]
Hi @janpe! Yes, that seems reasonable, but only for `webpack-config`. Both `xdl` and `expo-cli` are currently deprecated and not maintained anymore.

We are also cleaning up this repository and moving some packages around, so I'll move your patch to the right location.

**Comment by byCedric** [comment]
Merged through https://github.com/expo/expo-webpack-integrations/pull/4

**Pull request closed without merging**
