### PR TITLE
fix(xdl): fix LoggerDetach

### PR DESCRIPTION
**Pull request by dsokal**
I simplified `LoggerDetach` and fixed printing logs (with "extra fields") in Turtle at the same time.

### CODE REVIEW

**Comment by fson** [comment]
Unlike `bunyan`, `@expo/bunyan` adds a unique `id` field (a UUID) to each and every log record. This essential for Expo Dev Tools, as syncing logs to the browser using the GraphQL API relies on the log records having an ID. The simplest and lowest overhead way to ensure this is inside the logger, given that logs come from various sources.

Can you explain the rationale behind this change, as it’s not currently included in the description of the pull request?

**Comment by fson** [comment]
Another reason why we don’t use the “original” bunyan package is that it has `dtrace-provider` as an `optionalDependency`. `dtrace-provider` fails to install on Windows and Linux, causing an ugly warning to be printed, even though we don’t use the DTrace functionality in bunyan at all. That’s why we have this optional dependency removed in our fork.

The [`bunyan`](https://github.com/trentm/node-bunyan) repo also has been unmaintained for the past two years. We haven’t had any issues with this package during that time, but if we ever have in the future, we can quickly fix them in our fork.

**Comment by dsokal** [comment]
Fair enough. I thought there is no reason for having our own version of this package. Before making the change, I check out the commits in our fork - https://github.com/expo/bunyan-logger/commits/master It seemed to me that there are no commits made by anyone from the Expo team, so I thought the only reason for this is to have our fork just in case we need to fix some bug. 

I also didn't know that `@expo/bunyan` adds an id to every log record and that something relies on that.

I'll revert the changes then.

**Comment by fson** [comment]
@dsokal thanks for the explanation! Looks like the repositories just got mixed up, our fork of bunyan is at https://github.com/expo/node-bunyan, not https://github.com/expo/bunyan-logger (which seems to be a Koa middleware for bunyan, possibly used in universe/www?).

Anyway, glad we caught this early, that’s what code review is for ☺️

**Comment by dsokal** [comment]
Uh, TBH I didn't read the readme of https://github.com/expo/bunyan-logger so I didn't notice it's a Koa middleware and not the package I was looking for :D

**Pull request merged**
