### PR TITLE
fix(xdl): Check if Client is installed via application directory [iOS 13/Xcode 11 compatibility]

### PR DESCRIPTION
**Pull request by cruzach**
Revealed in  [933](https://github.com/expo/expo-cli/issues/933#issuecomment-523872521) that iOS 13 / Xcode 11 Command Line Tools resulted in a forever loop after installing the Expo Client onto the simulator. 

The loop we get stuck in was [`_waitForExpoAppInstalledOnCurrentBootedSimulatorAsync`](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Simulator.ts#L275). `_isExpoAppInstalledOnCurrentBootedSimulatorAsync` would continually return `falsy` because there was no longer `AppID/Library/Caches/Snapshots` directory, so the `glob` match would fail. 

This PR makes it so we search for the app in the App Store Application Directory, instead of the Data Directory

**new commit** I realized that the previous glob search would also match any other app that happened to be installed on the sim with a bundle name starting with "Exponent". Good news is we already handle that in `_expoVersionOnCurrentBootedSimulatorAsync` with some regex testing 😄

### CODE REVIEW

**Comment by ahansson89** [comment]
Can this get merged in? iOS 13 and XCode 11 is out now. Thanks!

**Comment by mosnicholas** [comment]
+1 -- we're seeing issues and are unable to load our projects on iOS 13 and XCode 11 either.

**Comment by kitingChris** [comment]
Problem still exists and a real blocker! When will this be merged?

**Comment by jordan-acosta** [comment]
For anyone who ends up here, the newly-released Expo SDK 35 supports iOS 13 and XCode 11: https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4

**Comment by cruzach** [comment]
@fson this was fixed in [this commit](https://github.com/expo/expo-cli/commit/5f209e26ba47d978ca7006d7b528db93930ae9e3#diff-71db691b019e067851e82c9e8a3a6bd6), not sure if you want to keep that as it is or merge this one?

**Comment by fson** [comment]
Let's ship this?

**Comment by cruzach** [comment]
Wfm, resolving conflicts now

**Pull request merged**
