### PR TITLE
improvement: fix a little typo in `expo upload:ios`

### PR DESCRIPTION
**Pull request by yokodev**
This is in regard to Issue #777 
Hi, I've changed the file I just don't know how to continue with the test plan... Any suggestions?

### CODE REVIEW

**Comment by fson** [comment]
You can run the CLI locally by first running `yarn start` in the root of the repo and then running `./packages/expo-cli/bin/expo.js build:ios`.

**Comment by yokodev** [comment]
I try your suggestion, but I'm using Linux  and so,  I wasn't able to test it out  
Screenshot from 2019-07-04 15-37-03

So I'm not sure how should I continue with this.

**Comment by fson** [comment]
I see. `upload:ios` is currently only available for macOS.

**Comment by fson** [comment]
Thanks @yokodev!

**Pull request merged**
