### PR TITLE
Potential fix for chunk.msg.match is not a function (#1363)

### PR DESCRIPTION
**Pull request by kevgrig**

### CODE REVIEW

**Comment by brentvatne** [comment]
tweaked it slightly, thanks!

**Comment by kevgrig** [comment]
@brentvatne Thanks! Your tweak is good. Just last night, I was thinking that this issue probably happens when a chunk of a message happens to be, for example, an integer, and gets coerced into a non-String, so I'm more confident this will work. Do you know of any estimate when this might get pushed into a new version of the Expo client (I'm presuming a local update to expo-cli won't be sufficient to pick it up?)?

**Comment by brentvatne** [comment]
this change only requires me to republish @expo/xdl and expo-cli, i plan on doing this later today after reviewing several more prs

**Comment by kevgrig** [comment]
@brentvatne Awesome, thanks! Cheers.

**Comment by kevgrig** [comment]
@brentvatne I upgraded to expo-cli@3.11.2 but still have the same problem; however, I noticed in my error message (below) that it still shows as xdl@57.2.1 even though the [latest publish](https://github.com/expo/expo-cli/commit/a19d624798eb2e5b8b27274aa6503477ec9e53af) seems to bring in xdl@57.4.1. I'm upgrading expo-cli with `sudo npm install --unsafe-perm -g expo-cli`; should I be doing something else to ensure xdl is upgraded?

```
/@expo/xdl@57.2.1/src/logs/PackagerLogsStream.ts:493
    if (chunk.msg.match(/\(node:.\d*\)/)) {
```

**Comment by kevgrig** [comment]
Nevermind, it looks like it works after `expo start -c`! Seemingly the hypothesis is confirmed, thanks for the quick turnaround!

**Pull request merged**
