### PR TITLE
Migrate all running/publishing config reading methods to new app.config.js

### PR DESCRIPTION
**Pull request by EvanBacon**

### CODE REVIEW

**Comment by skevy** [comment]
# [Codecov](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=h1) Report
> Merging [#1581](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=desc) into [master](https://codecov.io/gh/expo/expo-cli/commit/0ac2dbf5a73ced106704373368b5e07caff8c5da&el=desc) will **increase** coverage by `0.04%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #1581      +/-   ##
==========================================
+ Coverage   62.41%   62.45%   +0.04%     
==========================================
  Files          47       47              
  Lines        1402     1401       -1     
  Branches      417      413       -4     
==========================================
  Hits          875      875              
- Misses        504      512       +8     
+ Partials       23       14       -9     
```


| [Impacted Files](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [packages/config/src/Web.ts](https://codecov.io/gh/expo/expo-cli/pull/1581/diff?src=pr&el=tree#diff-cGFja2FnZXMvY29uZmlnL3NyYy9XZWIudHM=) | `17.05% <0.00%> (ø)` | :arrow_up: |
| [packages/android-manifest/src/Manifest.ts](https://codecov.io/gh/expo/expo-cli/pull/1581/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW5kcm9pZC1tYW5pZmVzdC9zcmMvTWFuaWZlc3QudHM=) | `69.79% <0.00%> (ø)` | :arrow_up: |
| [...ackages/webpack-config/src/addons/withDevServer.ts](https://codecov.io/gh/expo/expo-cli/pull/1581/diff?src=pr&el=tree#diff-cGFja2FnZXMvd2VicGFjay1jb25maWcvc3JjL2FkZG9ucy93aXRoRGV2U2VydmVyLnRz) | `53.84% <0.00%> (ø)` | :arrow_up: |
| [...ackages/webpack-config/src/addons/withReporting.ts](https://codecov.io/gh/expo/expo-cli/pull/1581/diff?src=pr&el=tree#diff-cGFja2FnZXMvd2VicGFjay1jb25maWcvc3JjL2FkZG9ucy93aXRoUmVwb3J0aW5nLnRz) | `63.15% <0.00%> (ø)` | :arrow_up: |
| [...es/webpack-config/src/loaders/createBabelLoader.ts](https://codecov.io/gh/expo/expo-cli/pull/1581/diff?src=pr&el=tree#diff-cGFja2FnZXMvd2VicGFjay1jb25maWcvc3JjL2xvYWRlcnMvY3JlYXRlQmFiZWxMb2FkZXIudHM=) | `45.94% <0.00%> (ø)` | :arrow_up: |
| [...ck-config/src/plugins/ExpoInterpolateHtmlPlugin.ts](https://codecov.io/gh/expo/expo-cli/pull/1581/diff?src=pr&el=tree#diff-cGFja2FnZXMvd2VicGFjay1jb25maWcvc3JjL3BsdWdpbnMvRXhwb0ludGVycG9sYXRlSHRtbFBsdWdpbi50cw==) | `88.88% <0.00%> (ø)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=footer). Last update [0ac2dbf...e1747e5](https://codecov.io/gh/expo/expo-cli/pull/1581?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo-cli/issues/1657

**Comment by rickysullivan** [comment]
Mother of God.

**Comment by rickysullivan** [comment]
So does this mean we can use `app.config.js` yet?

**Comment by brentvatne** [comment]
@rickysullivan - soon! we're working on some last details of it

**Pull request merged**
