### PR TITLE
Update Android uninstalling copy

### LINKED ISSUE #2756: Use "Expo client" instead of "Expo"
```
Uninstalling Expo from Android device.
Installing Expo on device
```

we probably do this elsewhere too

### PR DESCRIPTION
**Pull request by brooksbecton**
Fixes #2756

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks! we should also update the installing copy:

> Installing Expo on device

**Comment by brooksbecton** [comment]
May have found two more instances

One says, "_Opens your app in Expo on a connected Android device_"
Wasn't sure if these should say something like "_Opens your app the Expo client on a connected Android device_"

https://github.com/expo/expo-cli/blob/0d6eba36f29ef86e03e09ba394df1ebce3074b37/packages/expo-cli/src/urlOpts.ts#L21
https://github.com/expo/expo-cli/blob/0d6eba36f29ef86e03e09ba394df1ebce3074b37/packages/expo-cli/src/urlOpts.ts#L24

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
> One says, "Opens your app in Expo on a connected Android device"
> Wasn't sure if these should say something like "Opens your app the Expo client on a connected Android device"

i think the latter is indeed better wording! follow-up pr welcome! thanks for the help

**Comment by brooksbecton** [comment]
Would you mind adding a `hacktoberfest-accepted` label to this PR?
If not, I understand.

**Pull request merged**
