### PR TITLE
[xdl] treat Android emulator as device if a serial connection cannot be established

### PR DESCRIPTION
**Pull request by kherock**
When launching Android with an emulator running on a different host (achievable by setting `ADB_SERVER_SOCKET`  or `ANDROID_ADB_SERVER_ADDRESS`), Expo fails to launch with the following error:
```
error: could not connect to TCP port 5554: Cannot assign requested address
```

The changes in this PR allow `getAbdNameForEmulatorIdAsync` to fail, and when the emulator name is empty, it treats it as a device with a fallback name of `Emulator ***`. With these changes, Expo can successfully set up inside the emulator at the expense of some slightly noisier logs:

```
Opening on Android...
adb: could not connect to TCP port 5554: Cannot assign requested address
adb: could not connect to TCP port 5554: Cannot assign requested address
adb: could not connect to TCP port 5554: Cannot assign requested address
Opening exp://localhost:19000 on Emulator sdk_gphone_x86_64
```

### CODE REVIEW

**Comment by EvanBacon** [comment]
Can you please specify a bullet list test plan for how to repro this error, emulator logic can be tricky and I'd like to verify that this doesn't break existing device/emulator behavior.

**Comment by kherock** [comment]
My specific setup has expo running inside of a vscode dev container, but it should be reproducible using a VM or just two computers:

Set up env A (this one needs to be able to create an emulator window and should allow port 5037 through its firewall)
* start an adb server listening on all addresses:
```console
$ adb -a nodaemon server
```
* start an emulator instance

Set up env B (after taking note of env A's IP address)
* override address of the ADB server
```console
$ export ANDROID_ADB_SERVER_ADDRESS=xxx.xxx.xxx.xxx
```
* check that adb sees the emulator instance on env A
```console
$ adb devices
List of devices attached
emulator-5554   device
```
* start Expo project on Android
```
$ expo start --android
Starting project at /app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler.
Couldn't start project on Android: could not connect to TCP port 5554: Cannot assign requested address
```

**Comment by kherock** [comment]
Is there anything I can do to help this get merged?

**Comment by brentvatne** [comment]
@kherock - sorry we're in the process of working on a couple of releases, we'll revisit this when we have a bit more time. appreciate the pr!

**Comment by EvanBacon** [comment]
Closing as the source has moved to [@expo/cli](https://github.com/expo/expo/tree/main/packages/%40expo/cli).

**Pull request closed without merging**
