### PR TITLE
log message suggesting windows users to use other terminal instead of

### PR DESCRIPTION
**Pull request by Fahad-Mahmood**
cmd.exe added

### CODE REVIEW

**Comment by brentvatne** [comment]
hi there! does `os.platform() === 'win32'` not return `true` in powershell as well?

**Comment by Fahad-Mahmood** [comment]
> hi there! does `os.platform() === 'win32'` not return `true` in powershell as well?

I don't think this piece of code is executed after adding it to the file you mentioned.

**Comment by brentvatne** [comment]
i don't understand :(

**Comment by brentvatne** [comment]
i'm going to close this because it doesn't detect if the developer is using cmd.exe, it only detects if they are using windows

**Pull request closed without merging**
