### PR TITLE
Revert workbox upgrade

### PR DESCRIPTION
**Pull request by EvanBacon**
https://github.com/expo/expo-cli/pull/1942 found a regression where websites don't upgrade unless force refreshed.

### CODE REVIEW

**Comment by jaulz** [comment]
@EvanBacon what's the issue?

**Comment by EvanBacon** [comment]
Websites don't upgrade unless force refreshed (⌘+shift+R). They should update when the website is refreshed regularly.

**Comment by jaulz** [comment]
Hm, it's working perfectly fine on my side. Did you check if you really closed all other tabs before?

**Comment by jaulz** [comment]
@EvanBacon if you can help me to reproduce it I am happy to spend some time and check the issue

**Pull request merged**
